config/routes.rb
Rails.application.routes.draw do

  get '/terms', to: 'pages#terms'
  get '/team', to: 'pages#team'

  devise_for :users

  resources :equipment do
    resources :rentals, only: [ :new, :create ]
    resources :reviews, only: [ :new, :create, :index ]
  end

  namespace :account do
    resources :equipment
    resources :rentals, only: [ :index, :edit, :update, :destroy ]
  end

  mount Attachinary::Engine => "/attachinary"

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/equipment.rb
# == Schema Information
#
# Table name: equipment
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  category    :string
#  available   :boolean
#  price       :decimal(, )
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Equipment < ApplicationRecord


  # scope :title, -> (title) { where title: title }
  # scope :address, -> (address) { where address: address }
  # scope :starts_with, -> (name) { where("name like ?", "#{name}%")}


  belongs_to :user
  has_many :users, through: :rentals
  has_many :reviews

  has_attachment :photo

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :title, presence: true
  validates :description, presence: true
  validates :address, presence: true
  # validates :category, presence: true
  # validates :available, presence: true
  validates :price, presence: true
  validates :photo, presence: true

  # validates :user, presence: true

  def self.search(params)
    results = available.with_title(params[:title])
    results = results.with_address(params[:address])

    results
  end

  def self.available
    where(available: true)
  end

  def self.with_title(title)
    title.present? ? where("title ILIKE ?", "%#{title}%") : all
  end

  def self.with_address(address)
    address.present? ? where("address ILIKE ?", "%#{address}%") : all
  end
end

app/controllers/account/equipment_controller.rb
class Account::EquipmentController < Account::AccountController

  before_action :find_equipment, only: [:show, :edit, :update, :destroy]

  def index
    @equipment = current_user.equipment.all

    end

    def show
      # @equipment = Equipment.where.not(latitude: nil, longitude: nil)

      @hash = Gmaps4rails.build_markers(@equipment) do |equipment, marker|
        marker.lat equipment.latitude
        marker.lng equipment.longitude
      end
    end

    def new
      @equipment = Equipment.new
    end

    def create
      @equipment = Equipment.new(equipment_params)
      @equipment.user = current_user
      if @equipment.save
        redirect_to equipment_path(@equipment), notice: 'Eqiupment was successfully created.'
      else
        render :new
      end
    end

    def edit
    end

    def update
      @equipment.update(equipment_params)
      if @equipment.save
        redirect_to equipment_path(@equipment)
      else
        render :edit
      end
    end

    def destroy
      @equipment.destroy
      redirect_to account_equipment_index_path
    end

    private

    def equipment_params
      params.require(:equipment).permit(:title, :description, :category, :price, :photo, :address)
    end

    def find_equipment
      @equipment = current_user.equipment.find(params[:id])
    end
  end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController

  def index
    @equipment = Equipment.search(params)

    @hash = Gmaps4rails.build_markers(@equipment) do |equipment, marker|
      marker.lat equipment.latitude
      marker.lng equipment.longitude
    end
  end

  def show
    @equipment = Equipment.find(params[:id])
    @review = Review.new
    @reviews = Review.all
    # @equipment_coordinates = { lat: @equipment.latitude, lng: @equipment.longitude }
        @hash = Gmaps4rails.build_markers(@equipment) do |equipment, marker|
      marker.lat equipment.latitude
      marker.lng equipment.longitude
    end
  end

end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/index.html.erb
<div class="wrapper-grey">
  <div class="container">

    <% if @equipment.present? %>
    <div class="row">
      <div class="col-xs-12 col-md-8">
        <div class="title text-center">
          <h2>Available Equipment:</h2>
        </div>
        <div class="all-cards">
          <% @equipment.each do |e| %>
          <div class="col-xs-12 col-md-6">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path e.photo.path %>);">
              <div class="card-category", id="small-title"><%= e.title %></div>
              <div class="card-description-small", id="fix">
                <p><%= e.description %></p>
              </div>
              <%= cl_image_tag e.user.avatar.path, class: "card-user avatar" %>
              <%= link_to "", equipment_path(e), class: 'card-link'  %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-md-4">
      <div id="map-small" style="width: 100%; height: 470px;"></div>
      </div>
    </div>



    <% else %>
    <div class="wrapper-unavailable text-center">
      <h3>Sorry, there is no equipment matching your criteria.</h3>
      <p></p>
      <hr>
      <%= image_tag 'butters.png', width: 100 %>
      <p></p>
      <hr>
      <p><%= link_to "Search again", root_path, class: 'btn btn-primary' %></p>
    </div>
    <% end %>
  </div>
</div>




<% content_for(:after_js) do %>

<%= javascript_tag do %>
$(document).ready(function() {
var handler = Gmaps.build('Google');
handler.buildMap({ internal: { id: 'map-small' } }, function() {
markers = handler.addMarkers(<%= raw @hash.to_json %>);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();
if (markers.length == 0) {
handler.getMap().setZoom(2);
} else if (markers.length == 1) {
handler.getMap().setZoom(14);
}
});
});

<% end %>

<% end %>

app/views/equipment/show.html.erb
<div class="container padded">
  <div class="row">
    <div class="col-xs-12 col-sm-5">
      <% if @equipment.photo? %>
      <div id="equipment-image">
        <%= cl_image_tag @equipment.photo.path, width: 400, height: 400, crop: :fill %>
      </div>
      <% end %>
    </div>

    <div class="col-xs-12 col-sm-4">
      <div class="card-info text-xs-center", id="eq-info">
        <div class="card-header">
          <h4 class="card-title">Equipment info:</h4>
        </div>
        <ul id="description">
          <h3><%= @equipment.title %></h3>
          <hr>
          <li>Description: </li><%= @equipment.description %>
          <p></p>
          <li>Owner: </li><%= @equipment.user.first_name.capitalize + " " + @equipment.user.last_name.capitalize %>
          <p></p>
          <li>Price (per day):</li> £<%= @equipment.price %>
          <p></p>
          <li>Address: </li> <%= @equipment.address %>
        </ul>
      </div>
    </div>

    <% if @equipment.user == current_user %>
    <div class="col-xs-12 col-sm-3">
      <div class="text-center">
        <div class="card-header text-center", id="edit-info">
          <p><%= link_to "Edit this listing", edit_account_equipment_path(@equipment), class: 'btn btn-warning'  %></p>
          <p><%= link_to "Remove this listing", account_equipment_path(@equipment), method: 'delete', class: 'btn btn-danger'  %></p>
        </div>
      </div>
    </div>


    <% end %>
    <% unless @equipment.user == current_user %>
    <div class="col-xs-12 col-sm-3">
      <div class="card-header text-center", id="rent-header">
        <form>
          <div class="form-group">
            <label for="start_date">Like this equipment?</label>
          </div>
          <hr>
          <% unless current_user %>
          <%= link_to "Rent now", new_user_session_path, class: "btn btn-danger"  %>
          <p></p>
          <% else %>
          <%= link_to "Rent now", new_equipment_rental_path(@equipment), class: "btn btn-danger"  %>
          <% end %>
        </form>
      </div>
    </div>
    <% end %>
  </div>

  <hr>
  <div class="row">
    <div id="map" style="width: 100%; height: 500px;"></div>
  </div>
  <%= render 'reviews/review_form', equipment: @equipment, review: @review %>
  <% @equipment.reviews.each do |review| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="box-white">
        <p><strong><%= review.user.first_name.capitalize %>:</strong></p>
        <p><%= review.content %></p>
        <div class="stars starrr", data-rating="<%= review.rating %>"></div>
      </div>
    </div>
  </div>

  <% end %>
</div>


<script>
  <% content_for(:after_js) do %>

  <%= javascript_tag do %>
  $(document).ready(function() {
    var handler = Gmaps.build('Google');
    handler.buildMap( {provider: { scrollwheel: false } , internal: { id: 'map' } }, function() {
      markers = handler.addMarkers(<%= raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      if (markers.length == 0) {
        handler.getMap().setZoom(2);
      } else if (markers.length == 1) {
        handler.getMap().setZoom(14);
      }
    });
  });

  <% end %>

  <% end %>
</script>