config/routes.rb
Rails.application.routes.draw do

  get '/terms', to: 'pages#terms'
  get '/team', to: 'pages#team'

  devise_for :users

  resources :equipment do
    resources :rentals, only: [ :new, :create ]
    resources :reviews, only: [ :new, :create, :index ]
  end

  namespace :account do
    resources :equipment
    resources :rentals, only: [ :index, :edit, :update, :destroy ]
  end

  mount Attachinary::Engine => "/attachinary"

  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="banner" style="background: linear-gradient(-225deg, rgba(0,101,168,0) 0%, rgba(49, 112, 143, 0.3) 50%), url(<%= image_path 'banner.jpg' %>);">
  <div class="banner-content">
    <h1>Rent music equipment</h1>
    <h2>Play whenever, wherever. </h2>

    <div class="search-form">
      <%= form_tag(equipment_index_path, method: "get") do %>
      <%= text_field_tag :title, nil, placeholder: "Drum Kit", class: "input-field" %>
      <%= text_field_tag :address, nil, placeholder: "London", class: "input-field"  %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_cards.html.erb
<div class="wrapper-grey padded">
  <div class="header">
    <h3 class="text-center", id="popular">Popular rentals
      <% 5.times do %>
      <i class="fa fa-star" aria-hidden="true"></i>
      <% end %>
    </h3>
  </div>
  <div class="container">
    <div class="row">
      <% equipment.each do |current_equipment| %>
      <div class="col-xs-12 col-sm-4", id="popular-card">
        <%= link_to (equipment_path(current_equipment)) do %>
        <% if current_equipment.photo? %>
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path current_equipment.photo.path, crop: "fill" %>);">
          <% else %>
          <div class="card">
            <% end %>
<!--             <div class="rating"><%# current_equipment.reviews.rating %></div>
 -->            <div class="card-description">
              <h2><%= current_equipment.title %></h2>
              <p><%= current_equipment.description %></p>
            </div>
            <%= cl_image_tag current_equipment.user.avatar.path, class: "card-user avatar" %>
            <%= link_to "", equipment_path(current_equipment), class: 'card-link'  %>
          </div>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
    <div id="footer">
      <div class="container">
        <div class="row">
          <div class="col-xs-4">
            <ul class="icons list-inline">
              <li><a href=""><i class="fa fa-instagram"></i></a></li>
              <li><a href=""><i class="fa fa-facebook"></i></a></li>
              <li><a href=""><i class="fa fa-twitter"></i></a></li>
            </ul>
          </div>
          <div class="col-xs-8 text-right">
            <ul class="list-inline">
              <li><%= link_to "Team", team_path %></li> |
              <a href="mailto:petia_182@yahoo.com" target="_top">Contact Us</a> |
              <li><%= link_to "Terms & Conditions", terms_path %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

     <a href="/account/rentals" class="navbar-wagon-item navbar-wagon-link">Welcome, <%= current_user.first_name.capitalize %> ! </a>
<!--      <%# link_to "Home", root_path, class: "navbar-wagon-item navbar-wagon-link" %>
 -->
<!--     <!-- Notification -->
    <%# link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
<!--     <div class="badge-container">
      <i class="fa fa-envelope-o"></i>
      <div class="badge badge-blue">3</div>
    </div>
    <%# end %> -->

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
      <% if current_user %>
        <%= cl_image_tag current_user.avatar.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
      <% else %>
        <%= image_tag "butters.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
      <% end %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to root_path do %>
            <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
          <li>
            <%= link_to account_equipment_index_path do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Your Listings") %>
            <% end %>
          </li>

          <li>
            <%= link_to account_rentals_path do %>
            <i class="fa fa-headphones"></i> <%= t(".profile", default: "Your Rentals") %>
            <% end %>
          </li>


          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <% else %>

    <!-- Login text link -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "List new equipment"), new_account_equipment_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar2.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="images/lewagon.png" />
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Text link -->
    <%= link_to "Login", "#", class: 'navbar-wagon-item navbar-wagon-link' %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Login", new_user_session_path %></li>

          <li> <% link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <a href="" class="navbar-wagon-item navbar-wagon-button btn">List new equipment</a>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>